title: Test site, please ignore!
author: varrok
email: varrok@librem.one
description: > # this means to ignore newlines until "baseurl:"
  Test site, please ignore
theme: minima

# social links
github_username:  varr0k # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
